[default]
src = 'src'
out = 'out'
libs = ['node_modules', 'contracts']
remappings = [
    '@ensdomains/=node_modules/@ensdomains/',
    '@gnosis.pm/=node_modules/@gnosis.pm/',
    '@openzeppelin/=node_modules/@openzeppelin/',
    '@quant-finance/=node_modules/@quant-finance/',
    'eth-gas-reporter/=node_modules/eth-gas-reporter/',
    'hardhat-deploy/=node_modules/hardhat-deploy/',
    'hardhat/=node_modules/hardhat/',
    'ds-test/=lib/ds-test/src/',
    'forge-std/=lib/forge-std/src/',
    'contracts/=contracts/'
]
# See more config options https://github.com/gakonst/foundry/tree/master/config
